services:
    crizzo.ipanonym.listener:
        class: crizzo\ipanonym\event\permission_listener
        arguments:
            - '@auth'
        tags:
            - { name: event.listener }

    crizzo.ipanonym.task.anonymise_ips:
        class: crizzo\ipanonym\cron\task\task_anonymise
        arguments:
            - '@config'
            - '@dbal.conn'

    crizzo.ipanonym.cron.task.anonymise_ip:
        class: crizzo\ipanonym\cron\anonymise_ip
        arguments:
            - '@config'
            - '@log'
            - '@crizzo.ipanonym.task.anonymise_ips'
        calls:
            - [set_name, [crizzo.ipanonym.cron.task.anonymise_ip]]
        tags:
            - { name: cron.task }
